### ISSUE TITLE
stream related regression

### ISSUE THREAD

**Issue by sublimator** [interledgerjs/interledgerjs#110]
I deleted and recreated yarn.lock in the web-monetization-projects repo and some libraries were updated:
- ilp-protocol-ildcp
- ilp-packet
- oer-utils

This seems to cause a regression:
```
 coil-extension:background:StreamAttempt:ce20531c-fff2-4446-986c-e799cea1ff28:1  onConnectionError(%s) Error: Invalid response when sending packet 2: Invalid triggeredBy ILP address
    at Connection.<anonymous> (connection.js:1018)
    at Generator.next (<anonymous>)
    at fulfilled (connection.js:5)
Stream.ts:276  coil-extension:background:StreamAttempt:ce20531c-fff2-4446-986c-e799cea1ff28:1  cleanup()
Stream.ts:106  coil-extension:background:Stream  error streaming. retry in 2s. err= Invalid response when sending packet 2: Invalid triggeredBy ILP address Error: Invalid response when sending packet 2: Invalid triggeredBy ILP address
    at Connection.<anonymous> (chrome-extension://poahcjebhgbnlgdbigecpljijhjanafi/background.js:31540:23)
    at Generator.next (<anonymous>)
    at fulfilled (chrome-extension://poahcjebhgbnlgdbigecpljijhjanafi/background.js:30527:58)
```
Notable:
```
 onConnectionError(%s) Error: 
    Invalid response when sending packet 2: Invalid triggeredBy ILP address
```

@kincaidoneil, any ideas ? 

Investigation log:
* Error thrown is in new code:
   https://github.com/interledgerjs/interledgerjs/blame/master/packages/ilp-packet/src/index.ts#L330
  * "g.strata.tier2.coil.child.1.client." is an address that is invalid

**Comment by matdehaast** [comment]
@sublimator  wonder if the trailing `.` after client is causing the issue with the regex check

**Comment by sublimator** [comment]
I assumed so?

**Comment by sentientwaffle** [comment]
`ilp-packet`'s new (stricter) behavior is correct. coil's plugin returns an invalid `triggered_by` address for `F08` errors. I'm working on a fix for the plugin.

**Comment by matdehaast** [comment]
@sublimator I am closing this issue as it seems not to be a regression but rather doing the correct check

**Comment by sublimator** [comment]
Cheers!

Ja, was vague, but I think I meant a regression in the extension?
