### ISSUE TITLE
ilp-spsp-payout depends on vulnerable axios version

### ISSUE THREAD

**Issue by davebarr** [interledgerjs/interledgerjs#259]
When doing an npm audit, I noticed ilp-spsp-payout's package.json:

`"dependencies": {
    "axios": "^0.19.0",`

an npm audit warns:

├─ axios: 0.19.2
│  ├─ Issue: Server-Side Request Forgery in Axios
│  ├─ URL: https://github.com/advisories/GHSA-4w2v-q235-vp99
│  ├─ Severity: high
│  ├─ Vulnerable Versions: <0.21.1
│  ├─ Patched Versions: >=0.21.1
│  ├─ Via: axios
│  └─ Recommendation: Upgrade to version 0.21.1 or later

Would it be possible to bump the dependency and publish a new version?  Thanks!

**Comment by sublimator** [comment]
Closed in https://github.com/interledgerjs/interledgerjs/pull/313
